# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year/:month/:title.html 
auto: true
pygments: true
markdown: Maruku
var:
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  rss_path: /atom.xml

production_url : http://mookrs.github.com # or your custom domain name
title : Mookrs

author : 
  name : Mookrs
  email : moookrs@gmail.com
  github : mookrs
  twitter : mookrs
  feedbuder : 

exclude: .rbenv-version
